export const changelogs = [
  {
    version: '1.2.0',
    date: '2026-05-15',
    description: [
      { content: '🎉 新增 AI 对话功能模块，适配多家大模型，支持上下文摘要与长期记忆' },
      { content: '🎉 新增提示词管理模块，支持预设与管理 AI 对话提示词模板' },
      { content: '🎉 新增 ProSearch 组件，支持配置化渲染搜索框，快速实现列表搜索功能' },
      { content: '🎉 新增数据大屏页面模板与 ScreenAdapter 屏幕适配组件，适配不同分辨率展示' },
      { content: '🎉 新增项目定价卡片页面模板，满足 SaaS 类项目定价展示需求' },
      { content: '🎉 新增上传、水印等效果案例页面，丰富功能演示场景' },
      { content: '🎉 新增 RequireRoles 角色守卫装饰器，支持接口级角色权限校验' },
      { content: '🎉 前后端同步新增防重复提交机制，含 axios 拦截器与 RepeatSubmit 装饰器' },
      { content: '🎉 crud-generator SKILL 支持 AI 一键生成 CRUD 前后端全栈代码' },
      { content: '🐛 修复 Docker 构建时包管理器锁文件不一致导致镜像构建失败的问题' },
      { content: '🐛 修复在线用户强退权限标识错误导致前端始终无操作权限的问题' },
      { content: '🐛 修正演示环境路由守卫白名单路径匹配逻辑，避免部分页面误拦截' },
      { content: '🐛 修复容器数据库时区偏移与时间精度不一致，统一为 Asia/Shanghai 秒级精度' },
      { content: '🐛 修复图标管理生产环境因 eager:true 导致异常并发无法打开的问题' },
      { content: '🐛 修复菜单管理添加外链时路径解析异常，确保外部链接正常跳转' },
      { content: '🐛 修复 IP 归属地查询结果异常显示 0 0 的问题' },
      { content: '🐛 修复多处未使用变量导致前端生产构建失败的问题' },
      { content: '🔧 在线用户支持多终端登录记录，追踪每终端的登录时间与 IP 地址' },
      { content: '🔧 前端构建与 Nginx 均开启 gzip 压缩，优化静态资源传输效率' },
      { content: '🔧 响应拦截器新增 stream 异常捕获，确保流式请求异常及时提示' },
      { content: '🔧 createTime 与 updateTime 字段统一时区与秒级精度，消除数据不一致' },
      { content: '🔧 各列表页适配移动端展示效果，提升多端使用体验' },
      { content: '🔧 抽离公共工具库，优化任务日志导出逻辑，提升代码复用性' },
      { content: '📦 其它细节优化' },
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-05',
    description: [
      { content: '🎉 新增全局请求日志输出功能，全接口自动记录请求与响应详情' },
      { content: '🎉 新增任务调度日志导出功能，支持执行记录导出为本地文件离线分析' },
      { content: '🎉 新增系统健康检查模块与监控页面，提供 /live /ready 双探针支持' },
      { content: '🎉 实现深色模式主题切换及圆形扩散过渡动画，CSS 变量全局控制' },
      { content: '🎉 新增 Vue 项目 JSX 语法支持，扩展组件编写方式' },
      { content: '🎉 新增 Docker 容器化交付与运维部署方案，多阶段构建 + 健康探针 + Nginx 一站式集成' },
      { content: '🎉 参照 Redis 设计思想封装 localStorage 工具，支持过期时间与命名空间' },
      { content: '🎉 新增容器化数据库自动备份脚本 backup_db.sh，支持定时备份与过期清理' },
      { content: '🐛 修复异常过滤器无法获取 requestId 的问题，确保错误日志可追踪' },
      { content: '🔧 迁移 Bull 至 BullMQ，重构任务队列模块，优化调度性能与稳定性' },
      { content: '🔧 重构部署架构为多容器集群模式，引入 Nginx 反向代理与负载均衡' },
      { content: '📦 其它细节优化' },
    ],
  },
  {
    version: '1.0.0',
    date: '2026-04-27',
    description: [
      { content: '🚀 云禾全栈管理系统正式发布，基于 NestJS + Vue3 + TS 架构' },
      // {content:"🚀 云禾全栈管理系统正式发布，基于 NestJS + Vue3 + TS 架构"},
    ],
  },
]
